/*
 * This file is generated by jOOQ.
 */
package lab4.database.jooq;


import lab4.database.jooq.tables.Points;
import lab4.database.jooq.tables.Users;
import lab4.database.jooq.tables.records.PointsRecord;
import lab4.database.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * s467432.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PointsRecord> POINTS_PKEY = Internal.createUniqueKey(Points.POINTS, DSL.name("points_pkey"), new TableField[] { Points.POINTS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PointsRecord, UsersRecord> POINTS__POINTS_USER_ID_FKEY = Internal.createForeignKey(Points.POINTS, DSL.name("points_user_id_fkey"), new TableField[] { Points.POINTS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
}
