/*
 * This file is generated by jOOQ.
 */
package lab4.database.jooq;


import java.util.Arrays;
import java.util.List;

import lab4.database.jooq.tables.Points;
import lab4.database.jooq.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class S467432 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s467432</code>
     */
    public static final S467432 S467432 = new S467432();

    /**
     * The table <code>s467432.points</code>.
     */
    public final Points POINTS = Points.POINTS;

    /**
     * The table <code>s467432.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private S467432() {
        super("s467432", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Points.POINTS,
            Users.USERS
        );
    }
}
