/*
 * This file is generated by jOOQ.
 */
package lab4.database.jooq;


import lab4.database.jooq.tables.Points;
import lab4.database.jooq.tables.Users;


/**
 * Convenience access to all tables in s467432.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>s467432.points</code>.
     */
    public static final Points POINTS = Points.POINTS;

    /**
     * The table <code>s467432.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
