/*
 * This file is generated by jOOQ.
 */
package lab4.database.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import lab4.database.jooq.Keys;
import lab4.database.jooq.S467432;
import lab4.database.jooq.tables.Users.UsersPath;
import lab4.database.jooq.tables.records.PointsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Points extends TableImpl<PointsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>s467432.points</code>
     */
    public static final Points POINTS = new Points();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PointsRecord> getRecordType() {
        return PointsRecord.class;
    }

    /**
     * The column <code>s467432.points.id</code>.
     */
    public final TableField<PointsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>s467432.points.user_id</code>.
     */
    public final TableField<PointsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>s467432.points.x</code>.
     */
    public final TableField<PointsRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>s467432.points.y</code>.
     */
    public final TableField<PointsRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>s467432.points.r</code>.
     */
    public final TableField<PointsRecord, Double> R = createField(DSL.name("r"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>s467432.points.hit</code>.
     */
    public final TableField<PointsRecord, Boolean> HIT = createField(DSL.name("hit"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>s467432.points.date</code>.
     */
    public final TableField<PointsRecord, LocalDateTime> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private Points(Name alias, Table<PointsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Points(Name alias, Table<PointsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>s467432.points</code> table reference
     */
    public Points(String alias) {
        this(DSL.name(alias), POINTS);
    }

    /**
     * Create an aliased <code>s467432.points</code> table reference
     */
    public Points(Name alias) {
        this(alias, POINTS);
    }

    /**
     * Create a <code>s467432.points</code> table reference
     */
    public Points() {
        this(DSL.name("points"), null);
    }

    public <O extends Record> Points(Table<O> path, ForeignKey<O, PointsRecord> childPath, InverseForeignKey<O, PointsRecord> parentPath) {
        super(path, childPath, parentPath, POINTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PointsPath extends Points implements Path<PointsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PointsPath(Table<O> path, ForeignKey<O, PointsRecord> childPath, InverseForeignKey<O, PointsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PointsPath(Name alias, Table<PointsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PointsPath as(String alias) {
            return new PointsPath(DSL.name(alias), this);
        }

        @Override
        public PointsPath as(Name alias) {
            return new PointsPath(alias, this);
        }

        @Override
        public PointsPath as(Table<?> alias) {
            return new PointsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : S467432.S467432;
    }

    @Override
    public Identity<PointsRecord, Integer> getIdentity() {
        return (Identity<PointsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PointsRecord> getPrimaryKey() {
        return Keys.POINTS_PKEY;
    }

    @Override
    public List<ForeignKey<PointsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.POINTS__POINTS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>s467432.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.POINTS__POINTS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public Points as(String alias) {
        return new Points(DSL.name(alias), this);
    }

    @Override
    public Points as(Name alias) {
        return new Points(alias, this);
    }

    @Override
    public Points as(Table<?> alias) {
        return new Points(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Points rename(String name) {
        return new Points(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Points rename(Name name) {
        return new Points(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Points rename(Table<?> name) {
        return new Points(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Points where(Condition condition) {
        return new Points(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Points where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Points where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Points where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Points where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Points where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Points where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Points where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Points whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Points whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
