/*
 * This file is generated by jOOQ.
 */
package lab4.database.jooq.tables.records;


import java.time.LocalDateTime;

import lab4.database.jooq.tables.Points;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PointsRecord extends UpdatableRecordImpl<PointsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>s467432.points.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>s467432.points.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>s467432.points.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>s467432.points.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>s467432.points.x</code>.
     */
    public void setX(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>s467432.points.x</code>.
     */
    public Double getX() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>s467432.points.y</code>.
     */
    public void setY(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>s467432.points.y</code>.
     */
    public Double getY() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>s467432.points.r</code>.
     */
    public void setR(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>s467432.points.r</code>.
     */
    public Double getR() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>s467432.points.hit</code>.
     */
    public void setHit(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>s467432.points.hit</code>.
     */
    public Boolean getHit() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>s467432.points.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>s467432.points.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PointsRecord
     */
    public PointsRecord() {
        super(Points.POINTS);
    }

    /**
     * Create a detached, initialised PointsRecord
     */
    public PointsRecord(Integer id, Integer userId, Double x, Double y, Double r, Boolean hit, LocalDateTime date) {
        super(Points.POINTS);

        setId(id);
        setUserId(userId);
        setX(x);
        setY(y);
        setR(r);
        setHit(hit);
        setDate(date);
        resetChangedOnNotNull();
    }
}
